ランニングフラグメント内のコードを簡略化
lion-king-IT/RunnersHigh pull request #11
Opened 2021-03-05 12:55 UTC by swimmy-reo

### 簡略化したこと
***
1. アニメーションを関数化
2. バイブレーションを関数化
3. GoogleMapのMarkerをisMyLocationEnableにすることで、Markerを逐一削除する処理をしなくて済むように

##### その他
移動距離の取得が、正確にできていなかったので改善
グラフの単位をmからkmに
撮った写真のセットの向きやサイズを改善

ちなみに、Git-flow運用に転換するためにmasterをマージしているので、実質の変更点はこちらから。
https://github.com/lion-king-IT/RunnersHigh/commit/a2ae9852514152eee91a417ad4837524aea0ab0a

2021-03-07 11:36 UTC, Naoki-Hidaka commented
Git flowに移行したいのであればmasterにPRを出すのではなく、developに対してPRを出すべきですね

2021-03-07 11:59 UTC, Naoki-Hidaka requested changes

2021-03-07 11:59 UTC, Naoki-Hidaka commented on app/src/main/java/com/reo/running/runnershigh/PhotoListAdapter.kt
> +                        setColorFilter(ContextCompat.getColor(context, R.color.perfect))
```
visibility = View.VISIBLE
```

に関しては全ての条件分岐で重複しているので、whenの外に書くのがいいかと思います

2021-03-07 11:59 UTC, Naoki-Hidaka commented on app/src/main/java/com/reo/running/runnershigh/fragments/ResultFragment.kt
> +    private var select = false
Booleanの命名はis~~~とか、has~~~とかが多いですね
なので今回の命名も
isSelectedが妥当かと思います

2021-03-09 12:00 UTC, dosukoi-android approved these changes
LGTM

2021-03-09 12:00 UTC, merged